// v1.12.0 — END-TO-END transcode smoke test.
//
// This is the test that would have caught v1.11.3 (and v1.10.0). It
// takes the REAL ffmpeg arg list from buildFfmpegArgs(), feeds it a
// tiny real video through the REAL bundled ffmpeg binary, and asserts
// the transcode produces output. If any flag is rejected by the
// bundled binary (the v1.11.3 failure mode), ffmpeg exits non-zero
// with 0 bytes and this test fails — before the release ships.
//
// FIDELITY NOTE: the real /remux route feeds ffmpeg an HTTP URL
// (WebTorrent's stream server), and the arg list includes
// `-reconnect` flags that are HTTP-protocol options — they're INVALID
// on a plain file input. So this test serves the fixture over a tiny
// local HTTP server, exactly matching the production input type. (An
// earlier draft fed a file path and got a false "Option reconnect not
// found" failure — caught here, fixed by matching reality.)
//
// Runs as part of `npm test`, which `dist:win` runs before building,
// so a broken arg list can never reach the packaged installer.

import { describe, it, expect, beforeAll, afterAll } from 'vitest'
import { spawn, spawnSync } from 'node:child_process'
import { createServer } from 'node:http'
import { mkdtempSync, existsSync, readFileSync, rmSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { createRequire } from 'node:module'
import { buildFfmpegArgs } from '../server/lib/ffmpeg-args.js'

const require = createRequire(import.meta.url)

let FFMPEG_PATH = null
try {
  FFMPEG_PATH = require('@ffmpeg-installer/ffmpeg').path
} catch {
  FFMPEG_PATH = null
}
const haveFfmpeg = !!(FFMPEG_PATH && existsSync(FFMPEG_PATH))
const d = haveFfmpeg ? describe : describe.skip

let workDir
let fixtureBytes
let server
let baseUrl

beforeAll(async () => {
  if (!haveFfmpeg) {
    console.warn('[transcode-smoke] ffmpeg binary not resolvable — SKIPPING. Must NOT be skipped on a release build.')
    return
  }
  workDir = mkdtempSync(join(tmpdir(), 'wf-transcode-smoke-'))
  const fixturePath = join(workDir, 'fixture.mkv')
  // ~1s HEVC + AAC MKV generated by the bundled binary itself. HEVC
  // forces the realistic transcode decode path; tiny so it's a few KB.
  const gen = spawnSync(FFMPEG_PATH, [
    '-y',
    '-f', 'lavfi', '-i', 'testsrc=duration=1:size=128x72:rate=10',
    '-f', 'lavfi', '-i', 'sine=frequency=440:duration=1',
    '-c:v', 'libx265', '-pix_fmt', 'yuv420p', '-c:a', 'aac', '-shortest',
    fixturePath,
  ], { encoding: 'buffer', maxBuffer: 64 * 1024 * 1024 })
  if (gen.status !== 0) {
    console.error('[transcode-smoke] fixture gen failed:', gen.stderr?.toString().slice(-2000))
  }
  fixtureBytes = readFileSync(fixturePath)

  // Serve the fixture over HTTP with byte-range support, mirroring the
  // WebTorrent stream server the real route points ffmpeg at.
  server = createServer((req, res) => {
    const total = fixtureBytes.length
    const range = req.headers.range
    if (range) {
      const m = /bytes=(\d+)-(\d*)/.exec(range)
      const start = m ? parseInt(m[1], 10) : 0
      const end = m && m[2] ? parseInt(m[2], 10) : total - 1
      res.writeHead(206, {
        'Content-Type': 'video/x-matroska',
        'Accept-Ranges': 'bytes',
        'Content-Range': `bytes ${start}-${end}/${total}`,
        'Content-Length': end - start + 1,
      })
      res.end(fixtureBytes.subarray(start, end + 1))
    } else {
      res.writeHead(200, {
        'Content-Type': 'video/x-matroska',
        'Accept-Ranges': 'bytes',
        'Content-Length': total,
      })
      res.end(fixtureBytes)
    }
  })
  await new Promise((resolve) => server.listen(0, '127.0.0.1', resolve))
  const port = server.address().port
  baseUrl = `http://127.0.0.1:${port}/fixture.mkv`
})

afterAll(() => {
  try { server?.close() } catch { /* ignore */ }
  if (workDir) { try { rmSync(workDir, { recursive: true, force: true }) } catch { /* ignore */ } }
})

// Run ffmpeg ASYNC (not spawnSync). Critical: the fixture is served by
// an in-process HTTP server on the same event loop — spawnSync would
// block that loop so the server could never answer ffmpeg's request,
// `-reconnect` would retry until timeout, and the test would hang. The
// real route has the same shape (server + ffmpeg in one process) and
// works precisely because everything is async.
function runFfmpeg(args, timeoutMs = 45_000) {
  return new Promise((resolve) => {
    const ff = spawn(FFMPEG_PATH, args, { stdio: ['ignore', 'pipe', 'pipe'] })
    let bytesOut = 0
    let stderr = ''
    ff.stdout.on('data', (c) => { bytesOut += c.length })
    ff.stderr.on('data', (c) => { stderr += c.toString() })
    const killer = setTimeout(() => { try { ff.kill('SIGKILL') } catch { /* ignore */ } }, timeoutMs)
    ff.on('exit', (status, signal) => {
      clearTimeout(killer)
      resolve({ status, signal, bytesOut, stderr })
    })
    ff.on('error', (e) => { clearTimeout(killer); resolve({ status: -1, signal: null, bytesOut, stderr: stderr + '\n' + e.message }) })
  })
}

d('transcode pipeline runs the real ffmpeg with the real args (v1.11.3 fence)', () => {
  it('produces non-zero output and is not rejected at arg-parse', async () => {
    expect(fixtureBytes?.length).toBeGreaterThan(0)
    // EXACT args the /remux route uses, pointed at the local HTTP fixture.
    const args = buildFfmpegArgs({ inputUrl: baseUrl, seekSec: 0, audioIdx: null, needsTranscode: true })
    const { status, bytesOut, stderr } = await runFfmpeg(args)
    // v1.11.3 signature — assert explicitly for an obvious failure message.
    expect(stderr).not.toMatch(/Unrecognized option/i)
    expect(stderr).not.toMatch(/Error splitting the argument list/i)
    expect(stderr).not.toMatch(/Option .* not found/i)
    expect(status).toBe(0)
    // The real assertion: actual fragmented-MP4 bytes came out (v1.11.3 = 0).
    expect(bytesOut).toBeGreaterThan(1024)
  }, 60_000)

  it('also runs the copy branch without arg-parse failure', async () => {
    const args = buildFfmpegArgs({ inputUrl: baseUrl, seekSec: 0, audioIdx: null, needsTranscode: false })
    const { stderr } = await runFfmpeg(args)
    expect(stderr).not.toMatch(/Unrecognized option/i)
    expect(stderr).not.toMatch(/Error splitting the argument list/i)
  }, 60_000)
})
